//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyTurtles.ASP.NET.MVC.VideoTutorials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int Id { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<Video> Videos { get; set; }
    }
}
