//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuckyTurtles.ASP.NET.MVC.VideoTutorials.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.Histories = new HashSet<History>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SourceLink { get; set; }
        public System.DateTime DatePublished { get; set; }
        public Nullable<int> Duration { get; set; }
        public int UserId { get; set; }
        public bool isApproved { get; set; }
        public Nullable<int> Rejected { get; set; }
        public Nullable<int> WatchCount { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual RejectMessage RejectMessage { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
